import type { GuidedSkillShortcut } from "@/lib/guided-skills/types"
import type { HumanHandoffBusinessDayCode } from "@/lib/human-handoff"
import type { PublicSurveyDefinition, SurveyModuleConfig, SurveyWidgetConfig } from "@/lib/surveys/types"

export interface AmbientDeviceAppearanceSettings {
    ambientMaxHeight?: number;
    ambientOverlayOpacity?: number;
    ambientWidth?: number;
    ambientInputWidth?: number;
    ambientSideMargin?: number;
    ambientBottomMargin?: number;
    ambientInputSize?: "sm" | "md" | "lg" | "xl";
    showAmbientIcon?: boolean;
    ambientIconUrl?: string;
    ambientIconType?: "library" | "custom";
    ambientLibraryIcon?: string;
    ambientIconColor?: string;
    ambientInputTextColor?: string;
    ambientPlaceholderText?: string;
    ambientTheme?: "light" | "dark" | "auto";
    enableAmbientRainbowBorder?: boolean;
    ambientBorderColorIdle?: string;
    ambientBorderColorFocused?: string;
    ambientClosedBgColor?: string;
    ambientInputBgColorIdle?: string;
    ambientInputBgColorFocused?: string;
    ambientClosedBorderColorIdle?: string;
    ambientClosedBorderColorFocused?: string;
    ambientAiBubbleColor?: string;
    ambientUserBubbleColor?: string;
    ambientBorderGradientColor1?: string;
    ambientBorderGradientColor2?: string;
    ambientBorderGradientColor3?: string;
    ambientBorderGradientColor4?: string;
    ambientBorderGradientShowWhenCollapsed?: boolean;
    ambientBorderGradientShowWhenOpen?: boolean;
    ambientBorderGradientShowWhenThinking?: boolean;
}

export interface LocalizedTextValue {
    tr?: string;
    en?: string;
}

export interface LocalizedStringListValue {
    tr?: string[];
    en?: string[];
}

export type PrivacyLanguageCode = "tr" | "en" | "de" | "es";

export type PrivacyDocumentType =
    | "kvkkNotice"
    | "gdprPrivacyNotice"
    | "explicitConsentLead"
    | "explicitConsentAppointment"
    | "explicitConsentMarketing"
    | "explicitConsentSpecialCategory"
    | "explicitConsentInternationalTransfer";

export type PrivacyConsentPurpose =
    | "basic_chat"
    | "chat_transcript_storage"
    | "lead_capture"
    | "appointment_request"
    | "marketing_contact"
    | "ai_processing"
    | "international_transfer"
    | "special_category_data";

export interface PrivacyComplianceDocument {
    type: PrivacyDocumentType;
    title: string;
    text: string;
    language: PrivacyLanguageCode;
    versionHash: string;
    textHash: string;
}

export interface PrivacyComplianceSettings {
    enabled: boolean;
    mode: "hybrid";
    frameworks: Array<"kvkk" | "gdpr" | "ccpa" | "tcpa">;
    language: PrivacyLanguageCode;
    shortNoticeByLanguage: Record<PrivacyLanguageCode, string>;
    documentsByLanguage: Record<PrivacyLanguageCode, Record<PrivacyDocumentType, PrivacyComplianceDocument>>;
    requiredConsents: Array<{
        purpose: PrivacyConsentPurpose;
        documentType: PrivacyDocumentType;
        requiredBefore: string;
        checkboxLabelByLanguage: Record<PrivacyLanguageCode, string>;
    }>;
    autoGeneratedFields: Record<string, string>;
}

export interface ClassicDeviceAppearanceSettings {
    bottomSpacing?: number;
    sideSpacing?: number;
    launcherAnimation?: string;
    launcherStyle?: string;
    launcherCollapse?: boolean;
    launcherText?: string;
    launcherTextLocalized?: LocalizedTextValue;
    launcherRadius?: number;
    launcherHeight?: number;
    launcherWidth?: number;
    fullImageLauncherWidth?: number;
    fullImageLauncherHeight?: number;
    launcherIcon?: "message" | "library" | "custom";
    launcherIconUrl?: string;
    launcherLibraryIcon?: string;
    launcherIconColor?: string;
    launcherBackgroundColor?: string;
    launcherShadow?: string;
    launcherType?: "standard" | "fullImage";
    launcherImageMode?: "image" | "lottie";
    launcherFullImageUrl?: string;
    launcherLottieUrl?: string;
    launcherHoverEffect?: "scale" | "opacity" | "none";
    viewMode?: string;
    modalSize?: string;
    classicInputVariant?: "default" | "artify";
}

export interface ChatbotSettings {
    companyName: string;
    welcomeTitle: string;
    welcomeTitleLocalized?: LocalizedTextValue;
    welcomeMessage: string;
    welcomeMessageLocalized?: LocalizedTextValue;
    brandColor: string;
    brandLogo: string;
    hideVionBranding?: boolean;
    headerLogo: string;
    headerLogoWidth: number;
    headerLogoHeight: number;
    headerBackgroundColor: string;
    headerTextColor: string;
    suggestedQuestions: string[];
    suggestedQuestionsLocalized?: LocalizedStringListValue;
    enableLeadCollection: boolean;
    enableSurveyManager?: boolean;
    enableHumanHandoff?: boolean;
    enableKvkkConsent?: boolean;
    enableGuided?: boolean;
    kvkkConsent?: {
        enabled: boolean;
        text: string;
        versionHash: string;
        rejectionContactText?: string;
    };
    privacyCompliance?: PrivacyComplianceSettings;
    enableInitialLeadCollection: boolean;
    enableInChatLeadCollection: boolean;
    leadFormConfig: {
        title?: string;
        subtitle?: string;
        nameLabel?: string;
        emailLabel?: string;
        phoneLabel?: string;
        submitButtonText?: string;
        nameEnabled?: boolean;
        emailEnabled?: boolean;
        phoneEnabled?: boolean;
        nameRequired?: boolean;
        emailRequired?: boolean;
        phoneRequired?: boolean;
        namePlaceholder?: string;
        emailPlaceholder?: string;
        phonePlaceholder?: string;
    } | null;
    industry: string;
    enableVoiceAssistant: boolean;
    enableBusinessHours?: boolean;
    timezone?: string;
    businessHoursStart?: string;
    businessHoursEnd?: string;
    voiceProvider: string;
    elevenLabsVoiceId: string;
    voiceInteractionMode?: "legacy" | "realtime";
    realtimeVoiceProvider?: "elevenlabs";
    elevenLabsAgentId?: string;
    elevenLabsServerLocation?: "global" | "eu-residency" | "us" | "in-residency";
    voiceLowLatencyMode?: boolean;
    voiceInputSensitivity?: "low" | "normal" | "high";
    voiceResponseLength?: "short" | "balanced" | "detailed";
    voiceProfile?: "support" | "sales" | "appointments" | "restaurant";
    theme: string;
    enableIndustryGreeting: boolean;
    initialLanguage: "auto" | "en" | "tr" | "de" | "es";
    engagement: {
        enabled: boolean;
        bubble: {
            messages: any[];
        };
    };
    enableProactiveMessaging?: boolean;
    enableAppointments: boolean;
    appointmentTypes: string[];
    appointmentSuccessMessage: string;
    availableDays: string[];
    enableAutoSpeak: boolean;
    preferredVoice: string;
    enablePersonalShopper: boolean;
    enableVisualDiagnosis: boolean;
    enableDigitalWaiter?: boolean;
    digitalWaiter?: {
        serviceMode?: "table_service" | "counter_service";
        menuUrl?: string;
        menuPdfUrl?: string;
        signatureDishes?: string[];
        aiSuggestionsEnabled?: boolean;
    } | null;
    leadCustomFields: {
        id: string;
        label: string;
        type: string;
        required: boolean;
        placeholder?: string;
        options?: string[];
    }[];
    salesOptimizationConfig: {
        enabled: boolean;
        autoOfferDelay: number;
        discountCode: string;
        discountAmount: number;
        discountType: "percent" | "amount";
        enableStockAlerts: boolean;
        enableCartRecovery: boolean;
        enableProductComparison: boolean;
        alertThreshold?: number;
        // New fields used in page.tsx
        discountCodes?: boolean;
        discountCodeConfig?: {
            autoOffer: boolean;
            offerAfterSeconds: number;
            codes: Array<{
                code: string;
                discount: number;
                type: "percent" | "amount";
                usageType?: "auto" | "code_only";
            }>;
        };
    };
    launcherIcon: "message" | "library" | "custom";
    // Error Handling
    errorMessage?: string;
    offlineMessage?: string;
    offlineMessageLocalized?: LocalizedTextValue;
    launcherIconUrl: string;
    launcherLibraryIcon: string;
    // Mobile Settings
    mobileBottomSpacing: number;
    mobileSideSpacing: number;
    mobileLauncherAnimation: string;
    interactionMode?: "launcher" | "always_open";
    chatDisplayMode?: "classic" | "ambient" | "sidecar";
    classicInputVariant?: "default" | "artify";
    viewMode?: "classic" | "wide" | string;
    modalSize?: string;
    sidecarWidth?: number;
    sidecarMinWidth?: number;
    sidecarMaxWidth?: number;
    sidecarGutter?: number;
    sidecarDesktopOnly?: boolean;
    sidecarAlwaysOpen?: boolean;
    enableClassicEntryOnboarding?: boolean;
    position?: "bottom-right" | "bottom-left" | "bottom-center";
    ambientMaxHeight?: number;
    ambientOverlayOpacity?: number;
    ambientWidth?: number;
    ambientInputWidth?: number;
    ambientSideMargin?: number;
    ambientBottomMargin?: number;
    ambientInputSize?: "sm" | "md" | "lg" | "xl";
    showAmbientIcon?: boolean;
    ambientIconUrl?: string;
    ambientIconType?: "library" | "custom";
    ambientLibraryIcon?: string;
    ambientIconColor?: string;
    ambientInputTextColor?: string;
    ambientPlaceholderText?: string;
    ambientPlaceholderTextLocalized?: LocalizedTextValue;
    ambientTheme?: 'light' | 'dark' | 'auto';
    enableAmbientRainbowBorder?: boolean;
    ambientBorderColorIdle?: string;
    ambientBorderColorFocused?: string;
    ambientClosedBgColor?: string;
    ambientInputBgColorIdle?: string;
    ambientInputBgColorFocused?: string;
    ambientClosedBorderColorIdle?: string;
    ambientClosedBorderColorFocused?: string;
    ambientAiBubbleColor?: string;
    ambientUserBubbleColor?: string;
    ambientBorderGradientColor1?: string;
    ambientBorderGradientColor2?: string;
    ambientBorderGradientColor3?: string;
    ambientBorderGradientColor4?: string;
    ambientBorderGradientShowWhenCollapsed?: boolean;
    ambientBorderGradientShowWhenOpen?: boolean;
    ambientBorderGradientShowWhenThinking?: boolean;
    ambientPerDeviceSettingsEnabled?: boolean;
    ambientDesktopSettings?: AmbientDeviceAppearanceSettings;
    ambientMobileSettings?: AmbientDeviceAppearanceSettings;
    classicPerDeviceSettingsEnabled?: boolean;
    classicDesktopSettings?: ClassicDeviceAppearanceSettings;
    classicMobileSettings?: ClassicDeviceAppearanceSettings;
    widgetLoaderStyle?: 'skeleton' | 'spinner' | 'pulsing-icon';
    enableContextAwareness?: boolean;
    enableDynamicContext?: boolean;
    dynamicContextMode?: "nocode" | "enterprise_adapter" | string;
    dynamicContextSelectors?: Array<{ id?: string; key?: string; selector?: string }>;
    enableDynamicSiteContext?: boolean;
    dynamicSiteContextCollectionMode?: "dom" | "dom_network";
    dynamicSiteContextCrawlTrigger?: "manual" | "hybrid" | "auto";
    dynamicSiteContextRouteScope?: "sidebar_safe" | "same_origin_all" | "allowlist";
    dynamicSiteContextAllowlist?: string[];
    dynamicSiteContextMaxRoutes?: number;
    dynamicSiteContextMaxDurationSec?: number;
    dynamicSiteContextHydrationWaitMs?: number;
    dynamicSiteContextExcludeSelectorPrefixes?: string[];
    dynamicSiteContextCapturePII?: boolean;
    dynamicSiteContextPresetMode?: "none" | "suggested" | "approved";
    dynamicSiteContextPresetId?: string;
    dynamicSiteContextPresetApprovedAt?: string;
    dynamicSiteContextPresetOverrides?: Record<string, unknown>;
    dynamicSiteContextNetworkAllowlist?: string[];
    dynamicSiteContextGraphqlOperationAllowlist?: string[];
    dynamicSiteContextSuggestedPresetId?: string;
    dynamicSiteContextResolvedPresetId?: string;
    dynamicSiteContextRuntimePreset?: Record<string, unknown> | null;
    guidedSkills?: GuidedSkillShortcut[];
    humanHandoffSettings?: {
        triggerOnUserRequest?: boolean;
        businessHoursEnabled?: boolean;
        businessHoursStart?: string;
        businessHoursEnd?: string;
        businessHoursTimezone?: string;
        businessDays?: HumanHandoffBusinessDayCode[];
    };
    surveyModuleConfig?: SurveyModuleConfig | null;
    surveyWidgetConfig?: (SurveyWidgetConfig & {
        activeSurvey?: PublicSurveyDefinition | null;
    }) | null;
    quickActions?: {
        enabled: boolean;
        buttons: QuickActionButton[];
    };
}

export type QuickActionModuleId =
    | "appointments"
    | "humanHandoff"
    | "leadCollection"
    | "visualDiagnosis"
    | "kvkkConsent"
    | "proactiveMessaging"
    | "digitalWaiter"
    | "surveyManager"
    | "custom";

export interface QuickActionButton {
    id: string;
    label: string;
    localizedLabel?: {
        tr?: string;
        en?: string;
    };
    moduleId: QuickActionModuleId;
    triggerMessage: string;
    visible: boolean;
    order: number;
}
