import type { GuidedSkillShortcut } from "@/lib/guided-skills/types"

export interface AmbientDeviceAppearanceSettings {
    ambientMaxHeight?: number;
    ambientOverlayOpacity?: number;
    ambientWidth?: number;
    ambientInputWidth?: number;
    ambientSideMargin?: number;
    ambientBottomMargin?: number;
    ambientInputSize?: "sm" | "md" | "lg" | "xl";
    showAmbientIcon?: boolean;
    ambientIconUrl?: string;
    ambientIconType?: "library" | "custom";
    ambientLibraryIcon?: string;
    ambientIconColor?: string;
    ambientInputTextColor?: string;
    ambientPlaceholderText?: string;
    ambientTheme?: "light" | "dark" | "auto";
    enableAmbientRainbowBorder?: boolean;
    ambientBorderColorIdle?: string;
    ambientBorderColorFocused?: string;
    ambientClosedBgColor?: string;
    ambientInputBgColorIdle?: string;
    ambientInputBgColorFocused?: string;
    ambientClosedBorderColorIdle?: string;
    ambientClosedBorderColorFocused?: string;
    ambientAiBubbleColor?: string;
    ambientUserBubbleColor?: string;
    ambientBorderGradientColor1?: string;
    ambientBorderGradientColor2?: string;
    ambientBorderGradientColor3?: string;
    ambientBorderGradientColor4?: string;
    ambientBorderGradientShowWhenCollapsed?: boolean;
    ambientBorderGradientShowWhenOpen?: boolean;
    ambientBorderGradientShowWhenThinking?: boolean;
}

export interface ClassicDeviceAppearanceSettings {
    bottomSpacing?: number;
    sideSpacing?: number;
    launcherAnimation?: string;
    launcherStyle?: string;
    launcherCollapse?: boolean;
    launcherText?: string;
    launcherRadius?: number;
    launcherHeight?: number;
    launcherWidth?: number;
    fullImageLauncherWidth?: number;
    fullImageLauncherHeight?: number;
    launcherIcon?: "message" | "library" | "custom";
    launcherIconUrl?: string;
    launcherLibraryIcon?: string;
    launcherIconColor?: string;
    launcherBackgroundColor?: string;
    launcherShadow?: string;
    launcherType?: "standard" | "fullImage";
    launcherImageMode?: "image" | "lottie";
    launcherFullImageUrl?: string;
    launcherLottieUrl?: string;
    launcherHoverEffect?: "scale" | "opacity" | "none";
    viewMode?: string;
    modalSize?: string;
}

export interface ChatbotSettings {
    companyName: string;
    welcomeTitle: string;
    welcomeMessage: string;
    brandColor: string;
    brandLogo: string;
    headerLogo: string;
    headerLogoWidth: number;
    headerLogoHeight: number;
    headerBackgroundColor: string;
    headerTextColor: string;
    suggestedQuestions: string[];
    enableLeadCollection: boolean;
    enableGuided?: boolean;
    enableInitialLeadCollection: boolean;
    enableInChatLeadCollection: boolean;
    leadFormConfig: {
        title?: string;
        subtitle?: string;
        nameLabel?: string;
        emailLabel?: string;
        phoneLabel?: string;
        submitButtonText?: string;
        nameEnabled?: boolean;
        emailEnabled?: boolean;
        phoneEnabled?: boolean;
        nameRequired?: boolean;
        emailRequired?: boolean;
        phoneRequired?: boolean;
        namePlaceholder?: string;
        emailPlaceholder?: string;
        phonePlaceholder?: string;
    } | null;
    industry: string;
    enableVoiceAssistant: boolean;
    enableBusinessHours?: boolean;
    timezone?: string;
    businessHoursStart?: string;
    businessHoursEnd?: string;
    voiceProvider: string;
    elevenLabsVoiceId: string;
    theme: string;
    enableIndustryGreeting: boolean;
    initialLanguage: "auto" | "en" | "tr" | "de" | "es";
    engagement: {
        enabled: boolean;
        bubble: {
            messages: any[];
        };
    };
    enableAppointments: boolean;
    appointmentTypes: string[];
    appointmentSuccessMessage: string;
    availableDays: string[];
    enableAutoSpeak: boolean;
    preferredVoice: string;
    enablePersonalShopper: boolean;
    enableVisualDiagnosis: boolean;
    leadCustomFields: {
        id: string;
        label: string;
        type: string;
        required: boolean;
        placeholder?: string;
        options?: string[];
    }[];
    salesOptimizationConfig: {
        enabled: boolean;
        autoOfferDelay: number;
        discountCode: string;
        discountAmount: number;
        discountType: "percent" | "amount";
        enableStockAlerts: boolean;
        enableCartRecovery: boolean;
        enableProductComparison: boolean;
        alertThreshold?: number;
        // New fields used in page.tsx
        discountCodes?: boolean;
        discountCodeConfig?: {
            autoOffer: boolean;
            offerAfterSeconds: number;
            codes: Array<{
                code: string;
                discount: number;
                type: "percent" | "amount";
                usageType?: "auto" | "code_only";
            }>;
        };
    };
    launcherIcon: "message" | "library" | "custom";
    // Error Handling
    errorMessage?: string;
    offlineMessage?: string;
    launcherIconUrl: string;
    launcherLibraryIcon: string;
    // Mobile Settings
    mobileBottomSpacing: number;
    mobileSideSpacing: number;
    mobileLauncherAnimation: string;
    interactionMode?: "launcher" | "always_open";
    chatDisplayMode?: "classic" | "ambient" | "sidecar";
    sidecarWidth?: number;
    sidecarMinWidth?: number;
    sidecarMaxWidth?: number;
    sidecarGutter?: number;
    sidecarDesktopOnly?: boolean;
    sidecarAlwaysOpen?: boolean;
    enableClassicEntryOnboarding?: boolean;
    position?: "bottom-right" | "bottom-left" | "bottom-center";
    ambientMaxHeight?: number;
    ambientOverlayOpacity?: number;
    ambientWidth?: number;
    ambientInputWidth?: number;
    ambientSideMargin?: number;
    ambientBottomMargin?: number;
    ambientInputSize?: "sm" | "md" | "lg" | "xl";
    showAmbientIcon?: boolean;
    ambientIconUrl?: string;
    ambientIconType?: "library" | "custom";
    ambientLibraryIcon?: string;
    ambientIconColor?: string;
    ambientInputTextColor?: string;
    ambientPlaceholderText?: string;
    ambientTheme?: 'light' | 'dark' | 'auto';
    enableAmbientRainbowBorder?: boolean;
    ambientBorderColorIdle?: string;
    ambientBorderColorFocused?: string;
    ambientClosedBgColor?: string;
    ambientInputBgColorIdle?: string;
    ambientInputBgColorFocused?: string;
    ambientClosedBorderColorIdle?: string;
    ambientClosedBorderColorFocused?: string;
    ambientAiBubbleColor?: string;
    ambientUserBubbleColor?: string;
    ambientBorderGradientColor1?: string;
    ambientBorderGradientColor2?: string;
    ambientBorderGradientColor3?: string;
    ambientBorderGradientColor4?: string;
    ambientBorderGradientShowWhenCollapsed?: boolean;
    ambientBorderGradientShowWhenOpen?: boolean;
    ambientBorderGradientShowWhenThinking?: boolean;
    ambientPerDeviceSettingsEnabled?: boolean;
    ambientDesktopSettings?: AmbientDeviceAppearanceSettings;
    ambientMobileSettings?: AmbientDeviceAppearanceSettings;
    classicPerDeviceSettingsEnabled?: boolean;
    classicDesktopSettings?: ClassicDeviceAppearanceSettings;
    classicMobileSettings?: ClassicDeviceAppearanceSettings;
    widgetLoaderStyle?: 'skeleton' | 'spinner' | 'pulsing-icon';
    enableContextAwareness?: boolean;
    enableDynamicContext?: boolean;
    dynamicContextMode?: "nocode" | "enterprise_adapter" | string;
    dynamicContextSelectors?: Array<{ id?: string; key?: string; selector?: string }>;
    enableDynamicSiteContext?: boolean;
    dynamicSiteContextCollectionMode?: "dom" | "dom_network";
    dynamicSiteContextCrawlTrigger?: "manual" | "hybrid" | "auto";
    dynamicSiteContextRouteScope?: "sidebar_safe" | "same_origin_all" | "allowlist";
    dynamicSiteContextAllowlist?: string[];
    dynamicSiteContextMaxRoutes?: number;
    dynamicSiteContextMaxDurationSec?: number;
    dynamicSiteContextHydrationWaitMs?: number;
    dynamicSiteContextExcludeSelectorPrefixes?: string[];
    dynamicSiteContextCapturePII?: boolean;
    dynamicSiteContextPresetMode?: "none" | "suggested" | "approved";
    dynamicSiteContextPresetId?: string;
    dynamicSiteContextPresetApprovedAt?: string;
    dynamicSiteContextPresetOverrides?: Record<string, unknown>;
    dynamicSiteContextNetworkAllowlist?: string[];
    dynamicSiteContextGraphqlOperationAllowlist?: string[];
    dynamicSiteContextSuggestedPresetId?: string;
    dynamicSiteContextResolvedPresetId?: string;
    dynamicSiteContextRuntimePreset?: Record<string, unknown> | null;
    guidedSkills?: GuidedSkillShortcut[];
}
