export type BubbleId = string;

export interface BubbleTrigger {
    type: 'time_delay' | 'page_url' | 'exit_intent' | 'user_segment' | 'manual';
    value?: string | number; // e.g., delay in seconds, or URL regex
}

export interface BubbleMessage {
    id: BubbleId;
    content: string; // The text to display
    trigger: BubbleTrigger;

    /**
     * Start and End times for this message to be active (optional)
     * ISO Date strings or HH:mm format for daily recurring
     */
    startTime?: string;
    endTime?: string;

    /**
     * Days of week this message is active (0=Sunday, 1=Monday...)
     */
    activeDays?: number[];

    /**
     * Priority (higher number = higher priority if multiple trigger)
     */
    priority?: number;

    /**
     * If true, this message was generated by AI (e.g. Digital Waiter)
     */
    isAiGenerated?: boolean;
}

export interface ProactiveConfig {
    isEnabled: boolean;
    bubbles: BubbleMessage[];
    aiSuggestionsEnabled: boolean; // Allow modules like Digital Waiter to inject bubbles
}
