import { computeContractVersionHash, type PublishedContractVersion } from "@/lib/contracts"

export const PRIVACY_LANGUAGES = ["tr", "en", "de", "es"] as const

export type PrivacyLanguage = (typeof PRIVACY_LANGUAGES)[number]
export type PrivacyConsentEventType =
    | "notice_shown"
    | "notice_acknowledged"
    | "continued_after_notice"
    | "explicit_consent_granted"
    | "explicit_consent_rejected"
    | "withdrawn"

export type PrivacyConsentPurpose =
    | "basic_chat"
    | "chat_transcript_storage"
    | "lead_capture"
    | "appointment_request"
    | "marketing_contact"
    | "ai_processing"
    | "international_transfer"
    | "special_category_data"

export type PrivacyDocumentType =
    | "kvkkNotice"
    | "gdprPrivacyNotice"
    | "explicitConsentLead"
    | "explicitConsentAppointment"
    | "explicitConsentMarketing"
    | "explicitConsentSpecialCategory"
    | "explicitConsentInternationalTransfer"

export interface PrivacyComplianceDocument {
    type: PrivacyDocumentType
    title: string
    text: string
    language: PrivacyLanguage
    versionHash: string
    textHash: string
}

export interface PrivacyRequiredConsent {
    purpose: PrivacyConsentPurpose
    documentType: PrivacyDocumentType
    requiredBefore: "lead_submit" | "appointment_submit" | "marketing_opt_in" | "special_category_submit" | "international_transfer"
    checkboxLabelByLanguage: Record<PrivacyLanguage, string>
}

export interface PrivacyCompliancePayload {
    enabled: boolean
    mode: "hybrid"
    frameworks: Array<"kvkk" | "gdpr" | "ccpa" | "tcpa">
    language: PrivacyLanguage
    shortNoticeByLanguage: Record<PrivacyLanguage, string>
    documentsByLanguage: Record<PrivacyLanguage, Record<PrivacyDocumentType, PrivacyComplianceDocument>>
    requiredConsents: PrivacyRequiredConsent[]
    autoGeneratedFields: Record<string, string>
}

const DEFAULT_SHORT_NOTICE: Record<PrivacyLanguage, string> = {
    tr: "Bu sohbet kapsamında paylaştığınız bilgiler hizmet sunumu, talebinize yanıt verilmesi ve güvenliğin sağlanması amacıyla işlenebilir. Lütfen özel nitelikli kişisel veri paylaşmayın. Aydınlatma metnini inceleyebilirsiniz. Sohbete devam ederek bu bilgilendirmeyi okuduğunuzu ve temel sohbet hizmeti kapsamında gerekli veri işlemeyi kabul ettiğinizi beyan etmiş olursunuz.",
    en: "Information you share in this chat may be processed to provide the service, respond to your request, and keep the service secure. Please do not share special category personal data. You can review the privacy notice. By continuing the chat, you confirm that you have read this notice and accept the necessary processing for the basic chat service.",
    de: "Informationen, die Sie in diesem Chat teilen, koennen zur Bereitstellung des Dienstes, zur Beantwortung Ihrer Anfrage und zur Sicherheit verarbeitet werden. Bitte teilen Sie keine besonderen Kategorien personenbezogener Daten. Sie koennen den Datenschutzhinweis einsehen. Wenn Sie den Chat fortsetzen, bestaetigen Sie, dass Sie diesen Hinweis gelesen haben und die erforderliche Verarbeitung fuer den Basis-Chatdienst akzeptieren.",
    es: "La informacion que comparta en este chat puede tratarse para prestar el servicio, responder a su solicitud y mantener la seguridad. No comparta datos personales de categorias especiales. Puede revisar el aviso de privacidad. Al continuar el chat, confirma que ha leido este aviso y acepta el tratamiento necesario para el servicio basico de chat.",
}

function normalizeText(value: unknown) {
    return typeof value === "string" ? value.replace(/\r\n/g, "\n").trim() : ""
}

function asRecord(value: unknown): Record<string, any> {
    return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, any> : {}
}

function pickString(data: Record<string, any>, keys: string[], fallback = "") {
    for (const key of keys) {
        const value = normalizeText(data[key])
        if (value) return value
    }
    return fallback
}

export function resolvePrivacyLanguage(input?: string | null): PrivacyLanguage {
    const normalized = String(input || "").trim().toLowerCase().split("-")[0]
    return PRIVACY_LANGUAGES.includes(normalized as PrivacyLanguage) ? normalized as PrivacyLanguage : "en"
}

export function buildPrivacyAutoGeneratedFields(mergedData?: Record<string, any> | null) {
    const data = mergedData || {}
    const companyName = pickString(data, ["companyName", "businessName", "name"], "Tenant")
    const contactEmail = pickString(data, ["privacyEmail", "supportEmail", "companyEmail", "leadNotificationEmail", "email"], "info@example.com")
    const contactPhone = pickString(data, ["phone", "companyPhone", "supportPhone"], "")
    const website = pickString(data, ["website", "websiteUrl", "domain", "url"], "")
    const address = pickString(data, ["address", "companyAddress"], "")
    const industry = pickString(data, ["sector", "sectorId", "industry"], "general")
    const retentionPeriod = pickString(data, ["privacyRetentionPeriod", "dataRetentionPeriod"], "the period required for the service and legal obligations")
    const aiProviderNote = pickString(data, ["privacyAiProviderNote", "aiProviderNote"], "AI service providers and infrastructure providers may process data only for service delivery.")

    return {
        companyName,
        dataControllerName: pickString(data, ["dataControllerName", "companyName", "businessName"], companyName),
        contactEmail,
        contactPhone,
        website,
        address,
        industry,
        retentionPeriod,
        aiProviderNote,
    }
}

function buildDefaultDocumentText(type: PrivacyDocumentType, language: PrivacyLanguage, fields: Record<string, string>, publishedKvkkText = "") {
    if (type === "kvkkNotice") {
        if (publishedKvkkText && language === "tr") return publishedKvkkText
        return [
            language === "tr" ? `${fields.dataControllerName} KVKK Aydinlatma Metni` : `${fields.dataControllerName} Privacy Notice`,
            "",
            language === "tr"
                ? `Veri sorumlusu: ${fields.dataControllerName}. Iletisim: ${fields.contactEmail}${fields.contactPhone ? `, ${fields.contactPhone}` : ""}.`
                : `Data controller: ${fields.dataControllerName}. Contact: ${fields.contactEmail}${fields.contactPhone ? `, ${fields.contactPhone}` : ""}.`,
            language === "tr"
                ? `Bu sohbet kapsaminda ad, soyad, iletisim bilgileri, mesaj icerigi, teknik loglar ve talep/randevu/lead bilgileri hizmet sunumu, taleplerin yanitlanmasi, guvenlik ve kalite iyilestirme amaclariyla islenebilir.`
                : `This chat may process identity, contact, message content, technical logs, request, appointment, and lead data to provide the service, respond to requests, maintain security, and improve quality.`,
            language === "tr"
                ? `Veriler hizmetin gerektirdigi sure ve yasal yukumlulukler boyunca saklanir. ${fields.aiProviderNote}`
                : `Data is retained for the period required by the service and legal obligations. ${fields.aiProviderNote}`,
        ].join("\n")
    }

    if (type === "gdprPrivacyNotice") {
        return [
            `${fields.dataControllerName} GDPR Privacy Notice`,
            "",
            `Controller: ${fields.dataControllerName}. Contact: ${fields.contactEmail}${fields.contactPhone ? `, ${fields.contactPhone}` : ""}.`,
            `We process chat messages, technical logs, contact details, lead and appointment information to provide the requested service, answer your questions, secure the service, and improve support quality.`,
            `Where consent is required, you can refuse or withdraw it without affecting the basic chat service. Data is retained for ${fields.retentionPeriod}. ${fields.aiProviderNote}`,
            `You may request access, correction, deletion, restriction, portability, or object to processing by contacting ${fields.contactEmail}.`,
        ].join("\n")
    }

    const trLabels: Record<PrivacyDocumentType, string> = {
        kvkkNotice: "",
        gdprPrivacyNotice: "",
        explicitConsentLead: "Iletisim bilgilerimin lead/talep kaydi olusturulmasi ve bu talebime donus yapilmasi amaciyla islenmesine acik riza veriyorum.",
        explicitConsentAppointment: "Randevu talebimin olusturulmasi ve benimle randevu hakkinda iletisime gecilmesi amaciyla kisisel verilerimin islenmesine acik riza veriyorum.",
        explicitConsentMarketing: "Kampanya, duyuru ve pazarlama iletileri icin benimle iletisime gecilmesine acik riza veriyorum.",
        explicitConsentSpecialCategory: "Paylasmam halinde ozel nitelikli kisisel verilerimin yalnizca talebimin degerlendirilmesi amaciyla islenmesine acik riza veriyorum.",
        explicitConsentInternationalTransfer: "Hizmetin saglanmasi icin gerekli teknik altyapi ve yapay zeka servisleri kapsaminda kisisel verilerimin yurt disina aktarilmasina acik riza veriyorum.",
    }
    const enLabels: Record<PrivacyDocumentType, string> = {
        kvkkNotice: "",
        gdprPrivacyNotice: "",
        explicitConsentLead: "I consent to the processing of my contact details to create a lead/request record and respond to my request.",
        explicitConsentAppointment: "I consent to the processing of my personal data to create my appointment request and contact me about the appointment.",
        explicitConsentMarketing: "I consent to being contacted for campaigns, announcements, and marketing communications.",
        explicitConsentSpecialCategory: "If I share special category data, I consent to its processing only to evaluate and respond to my request.",
        explicitConsentInternationalTransfer: "I consent to the international transfer of my personal data where required for technical infrastructure and AI services.",
    }
    return language === "tr" ? trLabels[type] : enLabels[type]
}

function documentTitle(type: PrivacyDocumentType, language: PrivacyLanguage) {
    const tr: Record<PrivacyDocumentType, string> = {
        kvkkNotice: "KVKK Aydinlatma Metni",
        gdprPrivacyNotice: "GDPR Gizlilik Bildirimi",
        explicitConsentLead: "Lead Acik Riza Metni",
        explicitConsentAppointment: "Randevu Acik Riza Metni",
        explicitConsentMarketing: "Pazarlama Izni",
        explicitConsentSpecialCategory: "Ozel Nitelikli Veri Riza Metni",
        explicitConsentInternationalTransfer: "Yurt Disi Aktarim Riza Metni",
    }
    const en: Record<PrivacyDocumentType, string> = {
        kvkkNotice: "KVKK Privacy Notice",
        gdprPrivacyNotice: "GDPR Privacy Notice",
        explicitConsentLead: "Lead Consent Text",
        explicitConsentAppointment: "Appointment Consent Text",
        explicitConsentMarketing: "Marketing Consent",
        explicitConsentSpecialCategory: "Special Category Data Consent",
        explicitConsentInternationalTransfer: "International Transfer Consent",
    }
    return language === "tr" ? tr[type] : en[type]
}

function buildDocument(type: PrivacyDocumentType, language: PrivacyLanguage, text: string): PrivacyComplianceDocument {
    const normalizedText = normalizeText(text)
    const textHash = computeContractVersionHash(`${type}:${language}:${normalizedText}`)
    return {
        type,
        title: documentTitle(type, language),
        text: normalizedText,
        language,
        textHash,
        versionHash: computeContractVersionHash(`privacy:${type}:${language}:${textHash}`),
    }
}

function getDocumentOverride(settings: Record<string, any>, language: PrivacyLanguage, type: PrivacyDocumentType) {
    const documents = asRecord(settings.documentsByLanguage)
    const languageDocs = asRecord(documents[language])
    const value = languageDocs[type]
    if (typeof value === "string") return normalizeText(value)
    return normalizeText(asRecord(value).text)
}

export function resolvePrivacyCompliancePayload(input: {
    mergedData?: Record<string, any> | null
    publishedKvkkContract?: PublishedContractVersion | null
    language?: string | null
}): PrivacyCompliancePayload {
    const mergedData = input.mergedData || {}
    const settings = asRecord(mergedData.privacyComplianceSettings || mergedData.privacyCompliance)
    const enabled = mergedData.enableKvkkConsent === true
    const language = resolvePrivacyLanguage(input.language || mergedData.initialLanguage)
    const autoGeneratedFields = buildPrivacyAutoGeneratedFields(mergedData)
    const publishedKvkkText = input.publishedKvkkContract?.text || ""

    const shortNoticeByLanguage = PRIVACY_LANGUAGES.reduce((acc, lang) => {
        const settingsShort = asRecord(settings.shortNoticeByLanguage)
        acc[lang] = normalizeText(settingsShort[lang]) || DEFAULT_SHORT_NOTICE[lang]
        return acc
    }, {} as Record<PrivacyLanguage, string>)

    const documentTypes: PrivacyDocumentType[] = [
        "kvkkNotice",
        "gdprPrivacyNotice",
        "explicitConsentLead",
        "explicitConsentAppointment",
        "explicitConsentMarketing",
        "explicitConsentSpecialCategory",
        "explicitConsentInternationalTransfer",
    ]

    const documentsByLanguage = PRIVACY_LANGUAGES.reduce((acc, lang) => {
        acc[lang] = documentTypes.reduce((docs, type) => {
            const legacyKvkkText = type === "kvkkNotice"
                ? normalizeText(mergedData.kvkkConsentSettings?.customText) || normalizeText(mergedData.kvkkCustomText)
                : ""
            const text = getDocumentOverride(settings, lang, type)
                || (lang === "tr" ? legacyKvkkText : "")
                || buildDefaultDocumentText(type, lang, autoGeneratedFields, publishedKvkkText)
            docs[type] = buildDocument(type, lang, text)
            return docs
        }, {} as Record<PrivacyDocumentType, PrivacyComplianceDocument>)
        return acc
    }, {} as Record<PrivacyLanguage, Record<PrivacyDocumentType, PrivacyComplianceDocument>>)

    const requiredConsents: PrivacyRequiredConsent[] = [
        {
            purpose: "lead_capture",
            documentType: "explicitConsentLead",
            requiredBefore: "lead_submit",
            checkboxLabelByLanguage: Object.fromEntries(PRIVACY_LANGUAGES.map((lang) => [lang, documentsByLanguage[lang].explicitConsentLead.text])) as Record<PrivacyLanguage, string>,
        },
        {
            purpose: "appointment_request",
            documentType: "explicitConsentAppointment",
            requiredBefore: "appointment_submit",
            checkboxLabelByLanguage: Object.fromEntries(PRIVACY_LANGUAGES.map((lang) => [lang, documentsByLanguage[lang].explicitConsentAppointment.text])) as Record<PrivacyLanguage, string>,
        },
        {
            purpose: "marketing_contact",
            documentType: "explicitConsentMarketing",
            requiredBefore: "marketing_opt_in",
            checkboxLabelByLanguage: Object.fromEntries(PRIVACY_LANGUAGES.map((lang) => [lang, documentsByLanguage[lang].explicitConsentMarketing.text])) as Record<PrivacyLanguage, string>,
        },
        {
            purpose: "special_category_data",
            documentType: "explicitConsentSpecialCategory",
            requiredBefore: "special_category_submit",
            checkboxLabelByLanguage: Object.fromEntries(PRIVACY_LANGUAGES.map((lang) => [lang, documentsByLanguage[lang].explicitConsentSpecialCategory.text])) as Record<PrivacyLanguage, string>,
        },
        {
            purpose: "international_transfer",
            documentType: "explicitConsentInternationalTransfer",
            requiredBefore: "international_transfer",
            checkboxLabelByLanguage: Object.fromEntries(PRIVACY_LANGUAGES.map((lang) => [lang, documentsByLanguage[lang].explicitConsentInternationalTransfer.text])) as Record<PrivacyLanguage, string>,
        },
    ]

    return {
        enabled,
        mode: "hybrid",
        // US-first default. TR tenants can switch to ["kvkk", "gdpr"] in settings.
        frameworks: ["ccpa", "gdpr"],
        language,
        shortNoticeByLanguage,
        documentsByLanguage,
        requiredConsents,
        autoGeneratedFields,
    }
}
